#####
#Soubor: Makefile
#Autor: Jan Wrona, xwrona00@stud.fit.vutbr.cz
#Datum: 9.12.2013
#Projekt: Okruh 3: SHO Výrobní linka pro předmět IMS
#####

NAME=ims

latex: $(NAME).tex
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

clean:
	rm -f $(NAME).aux $(NAME).log $(NAME).out $(NAME).toc
